require 'simplecov'
SimpleCov.start
require "minitest/autorun"
require "minitest/pride"
require "mocha/minitest"
require "./lib/stat_tracker"
require "./lib/game_teams_manager"
require "./lib/game_team"
require "./lib/games_manager"
require "./lib/game"
require "./lib/teams_manager"
require "./lib/team"
require "./lib/game_teams_goals_manager"
require "./lib/game_teams_tackles_manager"
require "./lib/game_teams_wins_manager"
